# Generated by Django 3.1.1 on 2020-09-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.IntegerField()),
                ('credit_machine', models.IntegerField()),
                ('avantages', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_carte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_famille', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse_email', models.CharField(max_length=50)),
                ('identifiant', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('credit_client_en_temps', models.IntegerField()),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.abonnement')),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.carte')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_email', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_web', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('abonnement_requis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
                ('heure_de_debut', models.TimeField()),
                ('duree', models.IntegerField()),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.espace')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('conditions_d_utilisation', models.CharField(max_length=500)),
                ('fabricant', models.CharField(max_length=100)),
                ('date_d_achat', models.DateField()),
                ('fournisseur', models.CharField(max_length=100)),
                ('prix_d_achat', models.IntegerField()),
                ('modele', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
                ('cout_en_euros', models.IntegerField()),
                ('date_de_livraison', models.DateField()),
                ('fichier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_d_evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Type_de_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Type_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('nomenclature', models.CharField(max_length=50)),
                ('date_de_creation', models.DateField()),
                ('duree_de_validite', models.IntegerField()),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Possede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_delivrance', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.client')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_de_pret', models.TimeField()),
                ('heure_de_retour', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.client')),
            ],
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('fiche_technique', models.CharField(blank=True, max_length=500, null=True)),
                ('date_de_peremption', models.DateField(blank=True, null=True)),
                ('fabricant', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.prestation'),
        ),
        migrations.AddField(
            model_name='machine',
            name='qualification_requise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.qualification'),
        ),
        migrations.AddField(
            model_name='machine',
            name='type_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.type_machine'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type_d_evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.type_d_evenement'),
        ),
        migrations.AddField(
            model_name='client',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.prestation'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_de_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.type_de_client'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('date_d_achat', models.DateField(blank=True, null=True)),
                ('date_de_livraison', models.DateField(blank=True, null=True)),
                ('etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.etat')),
                ('outil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.outil')),
                ('panier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.panier')),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='type_de_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovfabmanager.type_de_client'),
        ),
    ]
